name: Run reproducer on each commit
on:
  push:
  workflow_dispatch:
jobs:
    gradle:
      runs-on: "ubuntu-latest"
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: "Start build cache server"
        run: |                  
          docker run --detach \
              --publish 5071:5071 \
              --volume /opt/build-cache-node:${{ github.workspace }}/build-cache/data \
              gradle/build-cache-node:18.0 \
              start
        working-directory: build-cache
      - name: "Run first build that is supposed to compile kts files and store results into build cache"
        run: "./gradlew tasks --build-cache --no-daemon"
      - name: "Second build with compiled kts (cached kts should build at approximately that speed)"
        run: "./gradlew tasks --build-cache --no-daemon"
      - name: "Remove compiled kts files"
        run: "rm -rf ~/.gradle/caches/8.5/kotlin-dsl"
      - name: "Build again without compiled kts files - this should be fast if kts results were in build cache"
        run: "./gradlew tasks --build-cache --no-daemon"
      - name: "Second build after files deleted - this will be fast again"
        run: "./gradlew tasks --build-cache --no-daemon"
